set(CMAKE_SYSTEM_NAME CommanderX16)
set(CMAKE_SYSTEM_VERSION 2021.9.12)
set(CMAKE_SYSTEM_PROCESSOR 65C02S)

set(CMAKE_C_COMPILER cl65)
SET(CMAKE_C_FLAGS "--target cx16")
set(CMAKE_ASM_COMPILER cl65)

set(CMAKE_C_COMPILER_WORKS TRUE)
